### ISSUE TITLE
panic using redis producer

### ISSUE THREAD

**Issue by predmond** [trivago/gollum#15]
It seems that prod.format is never initialized and that causes a panic:

```
Debug: Loading consumer.Kafka
Debug: Loading stream.Broadcast
Debug: Loading producer.Redis
Debug: Loading stream.Broadcast
Debug: Configuring stream.Broadcast for bidrequests
Debug: Configuring stream.Broadcast for events
Debug: Using fallback stream for *
Debug: Configuring producer.Redis
Debug: Using fallback stream for _DROPPED_
Debug: Configuring consumer.Kafka
Debug: Starting *producer.Redis
Debug: Starting *core.LogConsumer
Debug: Starting *consumer.Kafka
We be nice to them, if they be nice to us. (startup)
Initializing new client
client/metadata fetching metadata for all topics from broker localhost:9092
Connected to broker at localhost:9092 (unregistered)
client/brokers registered new broker #0 at swarm-wily64:9092
Successfully initialized new client
Connected to broker at swarm-wily64:9092 (registered as #0)
consumer/broker/0 added subscription to rtb.events/0
client/metadata fetching metadata for all topics from broker localhost:9092
PANIC:  runtime error: invalid memory address or nil pointer dereference
goroutine 7 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
github.com/trivago/gollum/shared.RecoverShutdown()
	/home/vagrant/swarm/go/src/github.com/trivago/gollum/shared/utilities.go:220 +0x389
panic(0xacd200, 0xc8200100c0)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/trivago/gollum/producer.(*Redis).getValueFieldAndKey(0xc820076f20, 0xc82023403e, 0xaff, 0xfc2, 0xbadd59fc5937d476, 0xbadd59fc5937d476, 0x7f2a15d854b8, 0xc820090b00, 0xecebad9c0, 0x26a0fdf2, ...)
	/home/vagrant/swarm/go/src/github.com/trivago/gollum/producer/redis.go:148 +0xb6
github.com/trivago/gollum/producer.(*Redis).storeHash(0xc820076f20, 0xc82023403e, 0xaff, 0xfc2, 0xbadd59fc5937d476, 0xbadd59fc5937d476, 0x7f2a15d854b8, 0xc820090b00, 0xecebad9c0, 0x26a0fdf2, ...)
	/home/vagrant/swarm/go/src/github.com/trivago/gollum/producer/redis.go:173 +0x47
github.com/trivago/gollum/producer.(*Redis).(github.com/trivago/gollum/producer.storeHash)-fm(0xc82023403e, 0xaff, 0xfc2, 0xbadd59fc5937d476, 0xbadd59fc5937d476, 0x7f2a15d854b8, 0xc820090b00, 0xecebad9c0, 0x26a0fdf2, 0xfa5ce0, ...)
	/home/vagrant/swarm/go/src/github.com/trivago/gollum/producer/redis.go:113 +0x31
github.com/trivago/gollum/core.(*ProducerBase).messageLoop(0xc820076f20, 0xc8200db6f0)
	/home/vagrant/swarm/go/src/github.com/trivago/gollum/core/producer.go:485 +0xc4
github.com/trivago/gollum/core.(*ProducerBase).MessageControlLoop(0xc820076f20, 0xc8200db6f0)
	/home/vagrant/swarm/go/src/github.com/trivago/gollum/core/producer.go:584 +0x63
github.com/trivago/gollum/producer.(*Redis).Produce(0xc820076f20, 0xc8200db3d0)
	/home/vagrant/swarm/go/src/github.com/trivago/gollum/producer/redis.go:249 +0x38f
main.multiplexer.run.func1()
	/home/vagrant/swarm/go/src/github.com/trivago/gollum/multiplexer.go:383 +0x3f
github.com/trivago/gollum/shared.DontPanic(0xc8200d9de0)
	/home/vagrant/swarm/go/src/github.com/trivago/gollum/shared/utilities.go:233 +0x3a
created by main.multiplexer.run
	/home/vagrant/swarm/go/src/github.com/trivago/gollum/multiplexer.go:384 +0x727

Master betrayed us. Wicked. Tricksy, False. (signal)
Filthy little hobbites. They stole it from us. (shutdown)
Debug: Closing consumer *core.LogConsumer
Debug: Closing consumer *consumer.Kafka
Debug: Waiting for consumers to close
Debug: Recieved stop command
Closing Client
Closed connection to broker localhost:9092
Closed connection to broker swarm-wily64:9092
consumer/broker/0 disconnecting due to error processing FetchRequest: kafka: broker not connected
kafka: error while consuming rtb.events/0: kafka: broker not connected
It's the only way. Go in, or go back. (flushing)
Debug: Closing producer *producer.Redis
Debug: Waiting for producers to close
Debug: Recieved stop command
Debug: All dependencies resolved
```

**Comment by predmond** [comment]
I hacked this in to make it work:
```
diff --git a/producer/redis.go b/producer/redis.go
index f2ca4ec..a580c70 100644
--- a/producer/redis.go
+++ b/producer/redis.go
@@ -93,6 +93,12 @@ func (prod *Redis) Configure(conf core.PluginConfig) error {
        }
        prod.fieldFormat = fieldFormat.(core.Formatter)
 
+       format, err := core.NewPluginWithType(conf.GetString("Formatter", "format.Forward"), conf)
+       if err != nil {
+               return err // ### return, plugin load error ###
+       }
+       prod.format = format.(core.Formatter)
+
        if conf.HasValue("KeyFormatter") {
                keyFormat, err := core.NewPluginWithType(conf.GetString("KeyFormatter", "format.Forward"), conf)
                if err != nil {
```

**Comment by arnecls** [comment]
The formatter is configured and set by the base class (prod.ProducerBase.Configure).

**Comment by arnecls** [comment]
Should work now. I also tested the key formatter support, seems to work now.
