### ISSUE TITLE
panic in kafka producer when shutting down

### ISSUE THREAD

**Issue by predmond** [trivago/gollum#16]
After ctrl-c I got a panic
```
^CMaster betrayed us. Wicked. Tricksy, False. (signal)
Filthy little hobbites. They stole it from us. (shutdown)
Debug: Closing consumer *core.LogConsumer
Debug: Closing consumer *consumer.Kafka
Debug: Waiting for consumers to close
Debug: Recieved stop command
Closing Client
Closed connection to broker localhost:9092
Closed connection to broker swarm-wily64:9092
consumer/broker/0 disconnecting due to error processing FetchRequest: kafka: broker not connected
kafka: error while consuming rtb.events/0: kafka: broker not connected
It's the only way. Go in, or go back. (flushing)
Debug: Closing producer *producer.Redis
Debug: Closing producer *producer.Kafka
Debug: Waiting for producers to close
Debug: Recieved stop command
Debug: All dependencies resolved
Debug: Recieved stop command
Debug: All dependencies resolved
Producer shutting down.
producer/broker/0 shut down
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4e0afa]

goroutine 524 [running]:
panic(0xacd200, 0xc8200100c0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/trivago/gollum/producer.(*Kafka).pollResults(0xc820077080)
	/home/vagrant/swarm/go/src/github.com/trivago/gollum/producer/kafka.go:274 +0x72a
github.com/trivago/gollum/producer.(*Kafka).(github.com/trivago/gollum/producer.pollResults)-fm()
	/home/vagrant/swarm/go/src/github.com/trivago/gollum/producer/kafka.go:466 +0x20
github.com/trivago/gollum/core.(*ProducerBase).tickerLoop(0xc820077080, 0xb2d05e00, 0xc8202aa280)
	/home/vagrant/swarm/go/src/github.com/trivago/gollum/core/producer.go:467 +0x5d
github.com/trivago/gollum/core.(*ProducerBase).tickerLoop.func1()
	/home/vagrant/swarm/go/src/github.com/trivago/gollum/core/producer.go:476 +0x32
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a
```

**Comment by arnecls** [comment]
Could not reproduce but as this happens during shutdown I assume that the channel was closed and a nil message was processed (would fit the panic message).

**Comment by arnecls** [comment]
Could reproduce it and fixed it.
Happened when producer.Kafka was not able to connect to any broker from start on.

**Comment by andygrunwald** [comment]
Fixed in https://github.com/trivago/gollum/commit/ed39af2433b3c11df9f77cbc374fbc8788c02df1
